name: CI pipeline

on:
  workflow_call:
    inputs:
      GO_VERSION:
        required: true
        type: string
      GO_LINT_ARG:
        required: false
        type: string
      GO_LINT_VER:
        required: false
        type: string
      GO_LINT_DIR:
        required: false
        type: string
      GO_TEST_ARG:
        required: false
        type: string
      GO_TEST_DIR:
        required: true
        type: string
      GO_LICENCES_DIR:
        required: true
        type: string

jobs:
  lint_job:
    name: Lint job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Tidy
        run: go mod tidy

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ inputs.GO_LINT_VER }}
          args: ${{ inputs.GO_LINT_ARG }}
          working-directory: ${{ inputs.GO_LINT_DIR }}
          skip-pkg-cache: true
          skip-build-cache: true

  test_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Tidy
        run: go mod tidy

      - name: Go test
        run: go test ${{ inputs.GO_TEST_ARG }} ${{ inputs.GO_TEST_DIR }}

  licenses_check:
    name: Licences check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Install Go licenses
        run: go install github.com/google/go-licenses@latest

      - name: Run Go licenses check
        run: go-licenses csv ${{ inputs.GO_LICENCES_DIR }}

  editor_config_check:
    name: Editor config check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run editor config check
        run: |
          npm install --save-dev editorconfig-checker
          pwd
          ./node_modules/.bin/editorconfig-checker .

  sonarcloud_check:
    name: Sonarcloud check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Run SonarCloud check
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  greet_job:
    name: Greet job
    needs:
      - editor_config_check
      - lint_job
      - test_job
      - licenses_check
      - sonarcloud_check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print the greet
        uses: ./.github/actions/greet-composite-action
        with:
          who-to-greet: 'Mona the Octocat'
